In [19]:
## Import all required modules

import pandas as pd
import numpy as np
import yfinance as yf
import math

In [31]:
## Load the Stock list
tickers = pd.read_csv('C:\\Users\\VISHAL\\Downloads\\top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

In [130]:
def fetch_market_cap(ticker_list):
    data = yf.download(ticker_list, period = '1d', group_by = 'ticker', auto_adjust = False)
    print(data)

    stocks_data =[]
    for ticker in tickers_list:
        latest_price = data[ticker]['Close'].iloc[-1]
        market_cap = yf.Ticker(ticker).info.get("marketCap", 'N/A')
        stocks_data.append({
            "Ticker" : ticker,
            "Market Cap" : market_cap,
            "Latest Price": latest_price,
        })
        
    stocks_df = pd.DataFrame(stocks_data)
    return  stocks_df
    
tickers_list = tickers['Ticker'].values.tolist()
df =fetch_market_cap(tickers_list)
df.head()

[*********************100%***********************]  50 of 50 completed

Ticker          ITC.NS                                          ONGC.NS  \
Price             Open   High    Low   Close Adj Close   Volume    Open
Date
2025-01-10  449.950012  452.0  442.5  443.75    443.75  4784132   264.0

Ticker                                 ...  SBICARD.NS              \
Price        High         Low   Close  ...         Low       Close
Date                                   ...
2025-01-10  266.5  258.470001  263.75  ...  718.150024  730.200012

Ticker                         INFY.NS                                \
Price        Adj Close  Volume    Open         High      Low   Close
Date
2025-01-10  730.200012  695289  1937.0  1973.300049  1932.25  1968.5

Ticker
Price      Adj Close   Volume
Date
2025-01-10    1968.5  3992282

[1 rows x 300 columns]

         Ticker      Market Cap  Latest Price
0   RELIANCE.NS  16878285094912   1247.250000
1        TCS.NS  15485244538880   4279.649902
2   HDFCBANK.NS  12753923211264   1667.550049
3       INFY.NS   8153586466816   1968.500000
4  ICICIBANK.NS   8831719440384   1250.900024

In [76]:
df

           Ticker      Market Cap  Latest Price
0     RELIANCE.NS  16932414685184   1251.250000
1          TCS.NS  15459556524032   4270.850098
2     HDFCBANK.NS  12771514122240   1669.400024
3         INFY.NS   8130390917120   1962.599976
4    ICICIBANK.NS   8872314011648   1256.650024
5   HINDUNILVR.NS   5738284449792   2441.899902
6         SBIN.NS   6701943095296    751.049988
7   BAJFINANCE.NS   4578937405440   7327.049805
8   BHARTIARTL.NS   9665269202944   1617.099976
9          ITC.NS   5577715482624    445.799988
10   KOTAKBANK.NS   3536340123648   1778.900024
11    ADANIENT.NS   2805232304128   2426.199951
12          LT.NS   4861221928960   3535.800049
13     HCLTECH.NS   5363401228288   1980.050049
14  ASIANPAINT.NS   2236121350144   2331.949951
15    AXISBANK.NS   3241665888256   1047.650024
16   SUNPHARMA.NS   4302838431744   1793.750000
17       WIPRO.NS   3162468777984    302.500000
18  ULTRACEMCO.NS   3187790839808  11050.049805
19    HDFCLIFE.NS   1318477758464    612.299988
20        ONGC.NS   3338811473920    265.540009
21        NTPC.NS   3047178371072    314.299988
22   POWERGRID.NS   2821801115648    303.299988
23  TATAMOTORS.NS   2884157571072    783.950012
24  INDUSINDBK.NS    743215661056    954.150024
25  ADANIGREEN.NS   1526210756608    963.150024
26       TITAN.NS   3083190927360   3475.350098
27    DIVISLAB.NS   1533906386944   5782.700195
28       TECHM.NS   1507381084160   1702.300049
29      MARUTI.NS   3663439593472  11655.000000
30   COALINDIA.NS   2294076145664    372.250000
31        BPCL.NS   1215432491008    280.200012
32    JSWSTEEL.NS   2214564462592    896.500000
33     DRREDDY.NS   1137994104832   1366.599976
34  BAJAJFINSV.NS   2722124267520   1707.000000
35  ADANIPORTS.NS   2444630425600   1132.449951
36       CIPLA.NS   1204299104256   1484.699951
37   BRITANNIA.NS   1191080230912   4944.899902
38     HAVELLS.NS   1008530292736   1608.099976
39    SHREECEM.NS    934154797056  25874.250000
40      GRASIM.NS   1603699605504   2389.750000
41   TATASTEEL.NS   1605120557056    128.669998
42  HEROMOTOCO.NS    827309948928   4141.000000
43         M&M.NS   3736556535808   3117.199951
44   EICHERMOT.NS   1395427901440   5090.500000
45         IOC.NS   1865410543616    132.070007
46     SBICARD.NS    692441513984    727.700012
47  PIDILITIND.NS   1497123258368   2943.350098
48       DMART.NS   2447504310272   3764.600098
49     HDFCAMC.NS    833940881408   3900.949951

In [80]:
df = df.sort_values(by ="Market Cap",ascending = False)
df

           Ticker      Market Cap  Latest Price
0     RELIANCE.NS  16932414685184   1251.250000
1          TCS.NS  15459556524032   4270.850098
2     HDFCBANK.NS  12771514122240   1669.400024
8   BHARTIARTL.NS   9665269202944   1617.099976
4    ICICIBANK.NS   8872314011648   1256.650024
3         INFY.NS   8130390917120   1962.599976
6         SBIN.NS   6701943095296    751.049988
5   HINDUNILVR.NS   5738284449792   2441.899902
9          ITC.NS   5577715482624    445.799988
13     HCLTECH.NS   5363401228288   1980.050049
12          LT.NS   4861221928960   3535.800049
7   BAJFINANCE.NS   4578937405440   7327.049805
16   SUNPHARMA.NS   4302838431744   1793.750000
43         M&M.NS   3736556535808   3117.199951
29      MARUTI.NS   3663439593472  11655.000000
10   KOTAKBANK.NS   3536340123648   1778.900024
20        ONGC.NS   3338811473920    265.540009
15    AXISBANK.NS   3241665888256   1047.650024
18  ULTRACEMCO.NS   3187790839808  11050.049805
17       WIPRO.NS   3162468777984    302.500000
26       TITAN.NS   3083190927360   3475.350098
21        NTPC.NS   3047178371072    314.299988
23  TATAMOTORS.NS   2884157571072    783.950012
22   POWERGRID.NS   2821801115648    303.299988
11    ADANIENT.NS   2805232304128   2426.199951
34  BAJAJFINSV.NS   2722124267520   1707.000000
48       DMART.NS   2447504310272   3764.600098
35  ADANIPORTS.NS   2444630425600   1132.449951
30   COALINDIA.NS   2294076145664    372.250000
14  ASIANPAINT.NS   2236121350144   2331.949951
32    JSWSTEEL.NS   2214564462592    896.500000
45         IOC.NS   1865410543616    132.070007
41   TATASTEEL.NS   1605120557056    128.669998
40      GRASIM.NS   1603699605504   2389.750000
27    DIVISLAB.NS   1533906386944   5782.700195
25  ADANIGREEN.NS   1526210756608    963.150024
28       TECHM.NS   1507381084160   1702.300049
47  PIDILITIND.NS   1497123258368   2943.350098
44   EICHERMOT.NS   1395427901440   5090.500000
19    HDFCLIFE.NS   1318477758464    612.299988
31        BPCL.NS   1215432491008    280.200012
36       CIPLA.NS   1204299104256   1484.699951
37   BRITANNIA.NS   1191080230912   4944.899902
33     DRREDDY.NS   1137994104832   1366.599976
38     HAVELLS.NS   1008530292736   1608.099976
39    SHREECEM.NS    934154797056  25874.250000
49     HDFCAMC.NS    833940881408   3900.949951
42  HEROMOTOCO.NS    827309948928   4141.000000
24  INDUSINDBK.NS    743215661056    954.150024
46     SBICARD.NS    692441513984    727.700012

In [ ]:
## Taking Top 10 Stocks as per the Market Cap

In [94]:
df.reset_index(inplace =True,drop =True)
df.head(10)

          Ticker      Market Cap  Latest Price
0    RELIANCE.NS  16932414685184   1251.250000
1         TCS.NS  15459556524032   4270.850098
2    HDFCBANK.NS  12771514122240   1669.400024
3  BHARTIARTL.NS   9665269202944   1617.099976
4   ICICIBANK.NS   8872314011648   1256.650024
5        INFY.NS   8130390917120   1962.599976
6        SBIN.NS   6701943095296    751.049988
7  HINDUNILVR.NS   5738284449792   2441.899902
8         ITC.NS   5577715482624    445.799988
9     HCLTECH.NS   5363401228288   1980.050049

In [ ]:
## Calculate the Portfolio size and Position size

In [126]:
portfolio_size = int(input("Enter the amount you want to invest:"))
position_size  = portfolio_size/len(df.head(10).index)
position_size

Enter the amount you want to invest: 1000000

100000.0

In [ ]:
##  Calculate number of shares to buy

In [128]:
df['Number of shares to buy'] =  df['Latest Price'].apply(lambda price : math .floor(
    position_size/price
))
df.head(10)

          Ticker      Market Cap  Latest Price  Number of shares to buy
0    RELIANCE.NS  16932414685184   1251.250000                       79
1         TCS.NS  15459556524032   4270.850098                       23
2    HDFCBANK.NS  12771514122240   1669.400024                       59
3  BHARTIARTL.NS   9665269202944   1617.099976                       61
4   ICICIBANK.NS   8872314011648   1256.650024                       79
5        INFY.NS   8130390917120   1962.599976                       50
6        SBIN.NS   6701943095296    751.049988                      133
7  HINDUNILVR.NS   5738284449792   2441.899902                       40
8         ITC.NS   5577715482624    445.799988                      224
9     HCLTECH.NS   5363401228288   1980.050049                       50